# This is a basic workflow to help you get started with Actions

name: compile

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Docker Image
    container: pspdev/pspdev:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install Dependencies
        run: |
          apk add cmake gmp mpc1 mpfr4 make zip curl
  
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build
        run: |
          make
          mkdir export 
          cp -R assets export
          cp EBOOT.PBP export
          zip -r build.zip export
          curl --upload-file build.zip https://transfer.sh/