name: PSPFunkin Compile Real

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: pspdev/pspdev:latest
    steps:
      - name: Install Dependencies
        run: |
          apk add cmake gmp mpc1 mpfr4 make zip curl --quiet
      - name: Checkout
        uses: actions/checkout@main
      - name: Build
        run: make --slient && mkdir export && cp -R assets export && cp EBOOT.PBP export
      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: build
          path: 'export/*'
