name: PSPFunkin Compile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    container: pspdev/pspdev:latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Install Dependencies And Compile
        run: apk add cmake gmp mpc1 mpfr4 gcc g++ --quiet && cd cht2bin && cmake -S . -B ./build && cmake --build ./build && cd .. && psp-cmake -S . -B ./build && cd build && make -j48 && mkdir export && cp -R build export
      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: build
          path: 'export/*'
