name: PSPFunkin Compile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    container: pspdev/pspdev:latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Install Dependencies And Compile
        run: apk add gmp mpc1 mpfr4 --quiet && make && mkdir export && cp -R assets export && cp EBOOT.PBP export
      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: build
          path: 'export/*'
